project:
  type: website
  resources: 
    - "*.pdf"

website:
  title: "Welcome"
  repo-url: https://github.com/zhaw-lsfm/quarto-thesis
  repo-actions: [edit, source, issue]
  navbar:
    left:
      - index.qmd
      - getting-started.qmd
      - manual.qmd
      - zhaw-requirements.qmd
      - text: "ðŸ–º Demo"
        menu:
        - href: template.pdf
          text: "pdf (for submission)"
          target: blank
        - href: template.html
          text: "html (for development)"
    right:
      - href: for-devs.qmd
        text: "For Developers / Contributors"
      - icon: github
        href: https://github.com/zhaw-lsfm/quarto-thesis


bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand




